CONFIG = {
    "MAX_FUNCTION_LENGTH": 50,
    "MAX_FUNCTION_PARAMS": 5,
    "MAX_NESTING_DEPTH": 4,
    "MAX_FILE_LINES": 500,
    "TODO_DENSITY": 0.01,
    "MAX_BRANCHES": 10,
    "MAX_LOOPS": 3,
}
